title:             YuKun's blogs
email:             78700194@qq.com
description:       宇坤的个人博客
author:            YuKun
baseurl:           ""
url:               "http://yukundream.com/"

# Social Profiles
twitter_username:  JYKMaster
github_username:   Sofabulous
facebook_username: 靳宇坤

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
